<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>src</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~B</string>
	<key>name</key>
	<string>BNF</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>([\w-]+|&lt;[\w-]+&gt;)\s+(::=)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.symbol.bnf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.bnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rule-name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>rule-name</key>
		<dict>
			<key>begin</key>
			<string>(?:(\w+)(\@))?(&lt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.rule-tag.core-parse.bnf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.tag.core-parse.bnf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.rule-name.start.bnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.rule-name.end.bnf</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\w+</string>
					<key>name</key>
					<string>constant.other.symbol.rule-identifier.bnf</string>
				</dict>
			</array>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.bnf</string>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.bnf</string>
		</dict>
	</dict>
	<key>scope</key>
	<string>text.bnf</string>
	<key>scopeName</key>
	<string>text.bnf</string>
	<key>uuid</key>
	<string>EC7D7A20-A4B3-453B-83AC-F71D8960ED01</string>
</dict>
</plist>
